WEB_Assignment_IT02_Team7/Models/PaymentTransaction.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace WEB_Assignment_IT02_Team7.Models
{
    public class PaymentTransaction
    {
        public int TransactionID { get; set; }

        public int? ParcelID { get; set; }

        public double? AmtTran { get; set; }

        [DataType(DataType.Currency)]
        [StringLength(3, ErrorMessage = "Currency code must be exactly 3 characters")]
        [RegularExpression(@"^[A-Za-z]{3}$", ErrorMessage = "Currency code must consist of 3 alphabetic characters")]
        [Display(Name = "Currency")]
        public string Currency { get; set; } = "SGD";

        [StringLength(4)]
        public string TranType { get; set; } = "CASH";

        public DateTime TranDate { get; set; }

        [Display(Name = "Payment Method")]
        public string PaymentMethod { get; set; }

        [Display(Name = "Cash Amount")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Cash Amount >= $0.01")]
        public double? CashAmt { get; set; }

        [Display(Name = "Voucher Amount")]
        public double? VoucherAmt { get; set; }

        [Display(Name = "Total Amount")]
        public double? TotalAmt { get; set; }
    }
}

WEB_Assignment_IT02_Team7/Controllers/FrontOfficeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WEB_Assignment_IT02_Team7.Models;
using WEB_Assignment_IT02_Team7.DAL;
using System.Globalization;
using System.Reflection;
using Newtonsoft.Json;

namespace WEB_Assignment_IT02_Team7.Controllers
{
    public class FrontOfficeController : Controller
    {
        private FrontOfficeDAL frontOfficeContext = new FrontOfficeDAL();
        private Dictionary<string, List<SelectListItem>> toCitiesByCountry = new Dictionary<string, List<SelectListItem>>();
        private Dictionary<string, List<SelectListItem>> fromCitiesByCountry = new Dictionary<string, List<SelectListItem>>();
        private List<SelectListItem> paymentMethods = new List<SelectListItem>();


        public FrontOfficeController()
        {
            List<SelectListItem> toCountriesSelectListItems = frontOfficeContext.GetToCountries();
            List<string> toCountryList = toCountriesSelectListItems.Select(item => item.Text).ToList();

            List<SelectListItem> fromCountriesSelectListItems = frontOfficeContext.GetFromCountries();
            List<string> fromCountryList = fromCountriesSelectListItems.Select(item => item.Text).ToList();

            foreach (string toCountry in toCountryList)
            {
                List<SelectListItem> toCityList = frontOfficeContext.GetToCitiesByCountry(toCountry);
                toCitiesByCountry.Add(toCountry, toCityList);
            }
            foreach (string fromCountry in fromCountryList)
            {
                List<SelectListItem> fromCityList = frontOfficeContext.GetFromCitiesByCountry(fromCountry);
                fromCitiesByCountry.Add(fromCountry, fromCityList);
            }
            paymentMethods.Add(new SelectListItem { Text = "Cash", Value = "CASH" });
            paymentMethods.Add(new SelectListItem { Text = "Cash Voucher", Value = "VOUC" });
            paymentMethods.Add(new SelectListItem { Text = "Cash & Cash Voucher", Value = "CASHVOUC" });
        }

        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Front Office Staff"))
            {
                return RedirectToAction("Index", "Home");
            }

            HttpContext.Session.Remove("Page");
            return View();
        }

        public ActionResult CreateParcelRecord()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Front Office Staff"))
            {
                return RedirectToAction("Index", "Home");
            }

            HttpContext.Session.Remove("Page");
            ViewData["ShowCompute"] = false;
            ViewData["FromCountriesList"] = frontOfficeContext.GetFromCountries();
            ViewData["ToCountriesList"] = frontOfficeContext.GetToCountries();
            ViewData["ToCountryCityDict"] = toCitiesByCountry;
            ViewData["FromCountryCityDict"] = fromCitiesByCountry;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateParcelRecord(Parcel parcel, string submitButton)
        {
            ViewData["FromCountriesList"] = frontOfficeContext.GetFromCountries();
            ViewData["ToCountriesList"] = frontOfficeContext.GetToCountries();
            ViewData["ToCountryCityDict"] = toCitiesByCountry;
            ViewData["FromCountryCityDict"] = fromCitiesByCountry;
            if (submitButton == "Compute")
            {
                if (ModelState.IsValid)
                {
                    ViewData["ShippingRate"] = $"S${frontOfficeContext.GetShippingRate(parcel):F2}/kg";
                    ViewData["FromCityCountry"] = $"{parcel.FromCity}, {parcel.FromCountry}";
                    ViewData["ToCityCountry"] = $"{parcel.ToCity}, {parcel.ToCountry}";
                    int transitDays = frontOfficeContext.GetTransitTime(parcel);
                    ViewData["TransitDays"] = transitDays;
                    DateTime transiteDateTime = DateTime.Now.AddDays(transitDays);
                    string formattedDate = transiteDateTime.ToString("d-MMM-yyyy");
                    parcel.TargetDeliveryDate = DateTime.ParseExact(formattedDate, "d-MMM-yyyy", CultureInfo.InvariantCulture);
                    double shippingRate = frontOfficeContext.GetShippingRate(parcel);
                    double rawDeliveryCharge = Math.Round(shippingRate * parcel.ParcelWeight, 2);
                    ViewData["RawDeliveryCharge"] = $"({shippingRate} x {parcel.ParcelWeight}) = S${rawDeliveryCharge}";
                    double roundedDeliveryCharge = Math.Round(rawDeliveryCharge, 0);
                    ViewData["RoundedDeliveryCharge"] = $"S${roundedDeliveryCharge:F2}";
                    parcel.DeliveryCharge = Math.Max(roundedDeliveryCharge, 5);
                    ViewData["FinalDeliveryCharge"] = $"S${parcel.DeliveryCharge:F2}";
                    ViewData["ShowCompute"] = true;
                }
                else
                {
                    ViewData["ShowCompute"] = false;
                }
            }
            else if (submitButton == "Create")
            {
                if (ModelState.IsValid)
                {
                    int transitDays = frontOfficeContext.GetTransitTime(parcel);
                    DateTime transiteDateTime = DateTime.Now.AddDays(transitDays);
                    string formattedDate = transiteDateTime.ToString("d-MMM-yyyy");
                    parcel.TargetDeliveryDate = DateTime.ParseExact(formattedDate, "d-MMM-yyyy", CultureInfo.InvariantCulture);
                    double shippingRate = frontOfficeContext.GetShippingRate(parcel);
                    double rawDeliveryCharge = Math.Round(shippingRate * parcel.ParcelWeight, 2);
                    double roundedDeliveryCharge = Math.Round(rawDeliveryCharge, 0);
                    parcel.DeliveryCharge = Math.Max(roundedDeliveryCharge, 5);

                    DeliveryHistory deliveryHistory = new DeliveryHistory();
                    deliveryHistory.Description = $"Received parcel by {HttpContext.Session.GetString("LoginID")} on {DateTime.Now.ToString("d MMM yyyy h:mmtt", CultureInfo.CreateSpecificCulture("en-GB"))}.";
                    parcel.ParcelID = frontOfficeContext.CreateParcel(parcel, deliveryHistory);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["ShowCompute"] = false;
                }
            }
            else if (submitButton == "Edit")
            {
                ModelState.Clear();
                ViewData["ShowCompute"] = false;
            }
            ViewData["SelectedToCity"] = parcel.ToCity;
            ViewData["SelectedFromCity"] = parcel.FromCity;
            return View(parcel);
        }

        public ActionResult ViewUnpaidParcels()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Front Office Staff"))
            {
                return RedirectToAction("Index", "Home");
            }

            HttpContext.Session.Remove("Page");
            List<Parcel> parcelList = frontOfficeContext.GetParcelCharges();
            return View(parcelList);
        }

        public ActionResult PaymentTransaction(int? parcelID, double? originalCharge, double? unpaidCharge)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Front Office Staff"))
            {
                return RedirectToAction("Index", "Home");
            }

            HttpContext.Session.SetString("Page", "Transact");

            if (parcelID == null || unpaidCharge <= 0)
            {
                RedirectToAction("ViewUnpaidParcels");
            }

            ParcelPayment parcelPayment = new ParcelPayment();
            parcelPayment.Parcels = frontOfficeContext.GetParcelDetails(parcelID.Value);
            ViewData["ParcelID"] = parcelID.Value;
            ViewData["FromCityCountry"] = $"{parcelPayment.Parcels.FromCity}, {parcelPayment.Parcels.FromCountry}";
            ViewData["ToCityCountry"] = $"{parcelPayment.Parcels.ToCity}, {parcelPayment.Parcels.ToCountry}";
            ViewData["ParcelWeight"] = $"{parcelPayment.Parcels.ParcelWeight}kg";
            ViewData["OriginalCharge"] = $"S${originalCharge:F2}";
            ViewData["UnpaidCharge"] = $"S${unpaidCharge:F2}";
            ViewData["Currency"] = parcelPayment.Parcels.Currency;
            ViewData["OriginalAmount"] = originalCharge;
            ViewData["UnpaidAmount"] = unpaidCharge;
            ViewData["PaymentMethods"] = paymentMethods;
            ViewData["CashVoucherValid"] = false;
            return View(parcelPayment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PaymentTransaction(ParcelPayment parcelPayment, int? parcelID, double? originalCharge, double? unpaidCharge, string submitButton)
        {
            parcelPayment.Parcels = frontOfficeContext.GetParcelDetails(parcelID.Value);
            ViewData["ParcelID"] = parcelID.Value;
            ViewData["FromCityCountry"] = $"{parcelPayment.Parcels.FromCity}, {parcelPayment.Parcels.FromCountry}";
            ViewData["ToCityCountry"] = $"{parcelPayment.Parcels.ToCity}, {parcelPayment.Parcels.ToCountry}";
            ViewData["ParcelWeight"] = $"{parcelPayment.Parcels.ParcelWeight}kg";
            ViewData["OriginalCharge"] = $"S${originalCharge:F2}";
            ViewData["UnpaidCharge"] = $"S${unpaidCharge:F2}";
            ViewData["Currency"] = parcelPayment.Parcels.Currency;
            ViewData["OriginalAmount"] = originalCharge;
            ViewData["UnpaidAmount"] = unpaidCharge;
            ViewData["PaymentMethods"] = paymentMethods;

WEB_Assignment_IT02_Team7/Views/FrontOffice/CreateParcelRecord.cshtml
@model WEB_Assignment_IT02_Team7.Models.Parcel
@{
    ViewData["Title"] = "CreateDeliveryOrder";
    var toCountryCityDict = ViewData["ToCountryCityDict"] as Dictionary<string, List<SelectListItem>>;
    var fromCountryCityDict = ViewData["FromCountryCityDict"] as Dictionary<string, List<SelectListItem>>;
    var previousToCity = ViewData["SelectedToCity"] as string;
    var previousFromCity = ViewData["SelectedFromCity"] as string;
}

<div class="createParcelForm">
    <h2 style="text-align:center;">Create Parcel Record</h2>
    <form asp-action="CreateParcelRecord" method="post">
        <div class="form-row">
            <div class="form-group col-md-3">
                <label asp-for="SenderName"></label>
                <div class="d-flex flex-column">
                    <input asp-for="SenderName" type="text" class="form-control disable-on-compute">
                    <span asp-validation-for="SenderName" class="text-danger mt-1"></span>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="SenderTelNo"></label>
                <div class="d-flex flex-column">
                    <input asp-for="SenderTelNo" type="text" class="form-control disable-on-compute">
                    <span asp-validation-for="SenderTelNo" class="text-danger mt-1"></span>
                </div>
            </div>
            <div class="form-group col-md-2.9">
                <label asp-for="ReceiverName"></label>
                <div class="d-flex flex-column">
                    <input asp-for="ReceiverName" type="text" class="form-control disable-on-compute">
                    <span asp-validation-for="ReceiverName" class="text-danger mt-1"></span>
                </div>
            </div>
            <div class="form-group col-md-2.9">
                <label asp-for="ReceiverTelNo"></label>
                <div class="d-flex flex-column">
                    <input asp-for="ReceiverTelNo" type="text" class="form-control disable-on-compute">
                    <span asp-validation-for="ReceiverTelNo" class="text-danger mt-1"></span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3">
                <div class="d-flex flex-column">
                    <label asp-for="ParcelWeight"></label>
                    <input asp-for="ParcelWeight" type="number" step="0.01" min="0.01" class="form-control disable-on-compute">
                    <span asp-validation-for="ParcelWeight" class="text-danger mt-1"></span>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="d-flex flex-column">
                    <label asp-for="FromCountry"></label>
                    <select asp-for="FromCountry" id="FromCountry" class="form-select disable-on-compute" asp-items="@ViewData["FromCountriesList"] as List<SelectListItem>">
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="d-flex flex-column">
                    <label asp-for="FromCity"></label>
                    <select asp-for="FromCity" id="FromCity" class="form-select disable-on-compute">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <div class="d-flex flex-column">
                    <label asp-for="DeliveryAddress"></label>
                    <input asp-for="DeliveryAddress" type="text" class="form-control disable-on-compute">
                    <span asp-validation-for="DeliveryAddress" class="text-danger mt-1"></span>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="d-flex flex-column">
                    <label asp-for="ToCountry"></label>
                    <select asp-for="ToCountry" id="ToCountry" class="form-select disable-on-compute" asp-items="@ViewData["ToCountriesList"] as List<SelectListItem>">
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <div class="d-flex flex-column">
                    <label asp-for="ToCity"></label>
                    <select asp-for="ToCity" id="ToCity" class="form-select disable-on-compute">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-11">
                <div class="d-flex flex-column">
                    <label asp-for="ItemDescription"></label>
                    <textarea asp-for="ItemDescription" class="form-control disable-on-compute"></textarea>
                </div>
            </div>
        </div>
        @if (!Convert.ToBoolean(ViewData["ShowCompute"]))
        {
            <div class="form-group col-md-3">
                <button type="submit" name="submitButton" value="Compute" class="btn btn-primary" style="margin-top: 20px;">Compute</button>
            </div>
        }
        @if (Convert.ToBoolean(ViewData["ShowCompute"]))
        {
            <hr class="custom-hr" />
            <h2 style="text-align: center; margin-bottom: 20px;">Compute Parcel</h2>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label asp-for="ParcelWeight"></label>
                    <span class="form-control">@Html.Display("ParcelWeight")</span>
                </div>
                <div class="form-group col-md-4">
                    <label>From City & Country</label>
                    <span class="form-control">@Html.Raw(ViewData["FromCityCountry"])</span>
                </div>
                <div class="form-group col-md-4">
                    <label>To City & Country</label>
                    <span class="form-control">@Html.Raw(ViewData["ToCityCountry"])</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label>Transit Days</label>
                    <span class="form-control">@Html.Raw(ViewData["TransitDays"])</span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="TargetDeliveryDate"></label>
                    <span class="form-control">@Html.Display("TargetDeliveryDate")</span>
                </div>
                <div class="form-group col-md-2">
                    <label>Shipping Rate</label>
                    <span class="form-control">@Html.Raw(ViewData["ShippingRate"])</span>
                </div>
                <div class="form-group col-md-1">
                    <label asp-for="Currency"></label>
                    <span class="form-control">@Html.Display("Currency")</span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Delivery Charge (Raw)</label>
                    <span class="form-control">@Html.Raw(ViewData["RawDeliveryCharge"])</span>
                </div>
                <div class="form-group col-md-3.5">
                    <label>Delivery Charge (Rounded)</label>
                    <span class="form-control">@Html.Raw(ViewData["RoundedDeliveryCharge"])</span>
                </div>
                <div class="form-group col-md-3.5">
                    <label>Delivery Charge (Final)</label>
                    <span class="form-control" data-toggle="tooltip" data-placement="top" title="Minimum delivery charge is S$5.00">
                        @Html.Raw(ViewData["FinalDeliveryCharge"])
                    </span>
                </div>
            </div>
            <div class="form-row">
                <div class="d-flex justify-content-between">
                    <div class="form-group">
                        <button type="submit" name="submitButton" value="Create" class="btn btn-primary" style="margin-top: 20px;">Create</button>
                    </div>
                    <div class="form-group d-flex justify-content-end">
                        <button type="submit" name="submitButton" value="Edit" class="btn btn-primary" style="margin-top: 20px;">Edit</button>
                    </div>
                </div>
            </div>
        }
    </form>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        var toCountryCityDict = @Html.Raw(Json.Serialize(toCountryCityDict));
        var fromCountryCityDict = @Html.Raw(Json.Serialize(fromCountryCityDict));
        var previousToCity = @Html.Raw(Json.Serialize(previousToCity));
        var previousFromCity = @Html.Raw(Json.Serialize(previousFromCity));

        function updateToCityOptions() {
            var selectedCountry = $('#ToCountry').val();
            var cities = toCountryCityDict[selectedCountry];
            $('#ToCity').empty();
            $.each(cities, function (index, city) {
                var option = $('<option>', {
                    value: city.value,
                    text: city.text
                });
                if (city.value === previousToCity) {
                    option.attr('selected', 'selected');
                }

                $('#ToCity').append(option);
            });
        }

        function updateFromCityOptions() {
            var selectedCountry = $('#FromCountry').val();
            var cities = fromCountryCityDict[selectedCountry];
            $('#FromCity').empty();
            $.each(cities, function (index, city) {
                var option = $('<option>', {
                    value: city.value,
                    text: city.text
                });
                if (city.value === previousFromCity) {
                    option.attr('selected', 'selected');
                }

                $('#FromCity').append(option);
            });
        }

        $('#ToCountry').change(function () {
            updateToCityOptions();
        }).trigger('change');

        $('#FromCountry').change(function () {
            updateFromCityOptions();
        }).trigger('change');

        window.onload = function () {
            updateToCityOptions();
            updateFromCityOptions();
        };

        var showCompute = @Json.Serialize(ViewData["ShowCompute"]);
        if (showCompute) {
            $('.disable-on-compute').addClass('readonly');
            $('.readonly').on('mousedown', function (e) {
                e.preventDefault();
                this.blur();
                return false;
            });
        }
        else {
            $('.disable-on-compute').removeClass('readonly')
        }
    });
</script>

WEB_Assignment_IT02_Team7/Views/FrontOffice/Index.cshtml
@{
    ViewData["Title"] = "Index";
    var role = Context.Session.GetString("Role");
    var name = Context.Session.GetString("Name");
}

<div class="container front-index-container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-8">
            <h2>Welcome @name!</h2>
            <h3>Here are the functions for @role:</h3>
            <ul class="list-group list-group-flush">
                <a href="~/FrontOffice/CreateParcelRecord" class="list-group-item list-group-item-action">Create Parcel Delivery Record</a>
                <a href="~/FrontOffice/CreateParcelRecord" class="list-group-item list-group-item-action">Compute Target Delivery Date</a>
                <a href="~/FrontOffice/CreateParcelRecord" class="list-group-item list-group-item-action">Calculate Delivery Charge</a>
                <a href="~/FrontOffice/ViewUnpaidParcels" class="list-group-item list-group-item-action">Create Payment Transaction</a>
            </ul>
        </div>
    </div>
</div>

WEB_Assignment_IT02_Team7/Views/FrontOffice/ViewUnpaidParcels.cshtml
@model IEnumerable<WEB_Assignment_IT02_Team7.Models.Parcel>

@{
    ViewData["Title"] = "ViewUnpaidParcels";
}

@if (Model.ToList().Count > 0)
{
    <div class="unpaidTable">
        <h2 class="text-center mb-2">Unpaid Parcels</h2>
        <div class="input-group mb-3">
            <div class="col-sm-4 mx-auto">
                <input type="text" class="form-control" style="margin-bottom: 10px;" id="searchInput" placeholder="Search by Parcel ID" onkeyup="filterTable()">
            </div>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Parcel ID</th>
                    <th>Original Delivery Charge ($)</th>
                    <th>Unpaid Delivery Charge ($)</th>
                    <th>Currency</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ParcelID</td>
                        <td>@string.Format("{0:F2}", item.DeliveryCharge)</td>
                        <td>@string.Format("{0:F2}", item.UnpaidDeliveryCharge)</td>
                        <td>@item.Currency</td>
                        <td>
                            <a class="btn btn-primary btn-sm btn-table"
                               asp-action="PaymentTransaction"
                               asp-controller="FrontOffice"
                               asp-route-parcelID="@item.ParcelID"
                               asp-route-originalCharge="@item.DeliveryCharge"
                               asp-route-unpaidCharge="@item.UnpaidDeliveryCharge">
                                Make Payment
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="noUnpaidParcels">
        <h2 class="text-center text-danger">No Unpaid Parcels</h2>
    </div>
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#searchInput").on("keyup", function () {
            var value = $(this).val().toUpperCase();
            $("table tbody tr").each(function () {
                var parcelId = $(this).find("td:first").text().toUpperCase();
                if (parcelId.includes(value)) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        });
    });
</script>

WEB_Assignment_IT02_Team7/Views/FrontOffice/_FrontOfficeMenu.cshtml
<nav class="navbar navbar-expand-md navbar-light">
	<a class="navbar-brand" href="~/FrontOffice/Index">
		<img id="NPCSLogo" src="~/assets/DeliveryIcon.png" alt="NPCS Logo" style="width:50px" />
	</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#commonNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="commonNavbar">
		<ul class="navbar-nav me-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/FrontOffice/CreateParcelRecord">
					Create Delivery Order
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="~/FrontOffice/ViewUnpaidParcels">Payment Transaction</a>
			</li>
		</ul>
		<ul class="navbar-nav ms-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/FrontOffice/LogOut">Log Out</a>
			</li>
		</ul>
	</div>
</nav>

WEB_Assignment_IT02_Team7/Views/FrontOffice/_TransactReturnMenu.cshtml
<nav class="navbar navbar-expand-md navbar-light">
	<a class="navbar-brand" href="~/FrontOffice/Index">
		<img id="NPCSLogo" src="~/assets/DeliveryIcon.png" alt="NPCS Logo" style="width:50px" />
	</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#commonNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="commonNavbar">
		<ul class="navbar-nav ms-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/FrontOffice/ViewUnpaidParcels">Return</a>
			</li>
		</ul>
	</div>
</nav>