WEB_Assignment_IT02_Team7/Controllers/StationManagerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WEB_Assignment_IT02_Team7.Models;
using WEB_Assignment_IT02_Team7.DAL;
using System.Globalization;
using System.Xml.Linq;

namespace WEB_Assignment_IT02_Team7.Controllers
{
    public class StationManagerController : Controller
    {
        private StationManagerDAL StationManagerContext = new StationManagerDAL();

        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

		public ActionResult AssignParcel()
		{
			if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
			{
				return RedirectToAction("Index", "Home");
			}
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AssignParcel(AssignDeliveryViewModel parcel)
		{
            int count = StationManagerContext.DeliveryManParcel(parcel.DeliveryManID);
			int id = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));

            List<Staff> dmlist = new List<Staff>();
            dmlist = StationManagerContext.GetDeliveryMan();

			if (ModelState.IsValid)
			{
				if (count <=5 )
				{
                    if (count == 5)
                    {
                        return View();
                    }

                    foreach(var item in dmlist)
                    {
                        if(item.StaffID == parcel.DeliveryManID)
                        {
                            if (StationManagerContext.CheckAssign(parcel.ParcelID))
                            {
                                DeliveryHistory deliveyHistory = new DeliveryHistory();
                                deliveyHistory.ParcelID = parcel.ParcelID;
                                deliveyHistory.Description = "Received by StationMgrSG on " + DateTime.Now.ToString("d MMMM yyyy h:mmtt");
                                StationManagerContext.AssignParcel(parcel);
                                deliveyHistory.RecordID = StationManagerContext.AddDeliveryHistory(deliveyHistory);
                                return RedirectToAction("Index");
                            }
                            return View(parcel);
                        }
                    }
				}

				if (StationManagerContext.CheckAssign(parcel.ParcelID))
				{
					TempData["ErrorMessage"] = "Error!";
					return View(parcel);
				}

				return View();
			}

			else
			{
				return View(parcel);
			}
		}



		public ActionResult DeliveryInformation()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
            {
                return RedirectToAction("Index", "Home");
            }

            ParcelViewModel parcelVM = new ParcelViewModel();
            parcelVM.ParcelList = null;
            return View(parcelVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeliveryInformation(ParcelViewModel parcelVM, string submitButton)
        {
            parcelVM.ParcelList = null;

            if (submitButton == "SearchParcel")
            {
                if (parcelVM.SearchedParcelID != null)
                {
                    parcelVM.ParcelList = StationManagerContext.GetParcelDetailsByID(parcelVM.SearchedParcelID);
                }
                else
                {
                    ViewData["Error"] = true;
                }
            }
            else if (submitButton == "SearchCustomer")
            {
                if (parcelVM.SearchedCustomerName != null)
                {
                    parcelVM.ParcelList = StationManagerContext.GetParcelDetailsByCustomerName(parcelVM.SearchedCustomerName);
                }
                else
                {
                    ViewData["Error"] = true;
                }
            }

            return View(parcelVM);
        }

        public ActionResult ViewDeliveryHistory(int? parcelID)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (parcelID == null)
            {
                return RedirectToAction("DeliveryInformation");
            }

            List<DeliveryHistory> deliveryHistoryList = StationManagerContext.GetDeliveryHistories(Convert.ToInt32(parcelID));
            return View(deliveryHistoryList);
        }

        public ActionResult RespondFeedback()
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
            {
                return RedirectToAction("Index", "Home");
            }

            List<FeedbackEnquiry> feedbackEnquiryList = StationManagerContext.GetAllFeedbackEnquiries();
            return View(feedbackEnquiryList);
        }

        public ActionResult CreateResponse(int? feedbackEnquiryID)
        {
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Station Manager"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (feedbackEnquiryID == null)
            {
                return RedirectToAction("RespondFeedback");
            }

            FeedbackEnquiry feedbackEnquiry = StationManagerContext.GetFeedbackEnquiryDetails(Convert.ToInt32(feedbackEnquiryID));
            return View(feedbackEnquiry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateResponse(FeedbackEnquiry feedbackEnquiry, int? feedbackEnquiryID)
        {
            feedbackEnquiry.FeedbackEnquiryID = Convert.ToInt32(feedbackEnquiryID);

            if (ModelState.IsValid)
            {
                feedbackEnquiry.Status = '1';
                feedbackEnquiry.StaffID = Convert.ToInt32(HttpContext.Session.GetInt32("StaffID"));
                StationManagerContext.UpdateFeedbackEnquiryResponse(feedbackEnquiry);
                return RedirectToAction("Index");
            }
            return View(feedbackEnquiry);
        }

        public ActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

WEB_Assignment_IT02_Team7/Views/StationManager/AssignParcel.cshtml
@model WEB_Assignment_IT02_Team7.Models.AssignDeliveryViewModel

@{
	ViewData["Title"] = "AssignParcel";
}

<style>
	/* Center the content horizontally */
	.text-center {
		display: flex;
		justify-content: center;
		align-items: center;
		height: 90vh; /* Set the container height to the full viewport height */
	}

	/* Style the form content container */
	.FormContent {
		max-width: 400px; /* Adjust the width as needed */
		margin: 0 auto; /* Center the form horizontally */
		padding: 20px;
		padding-top: 30px; /* Add padding on top */
		border: 1px solid #ccc;
		border-radius: 5px;
		box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
		background-color: #f4f4f4; /* Set light grey color as background */
	}

	/* Style the labels */
	.col-form-label {
		font-weight: bold;
		color: #333;
	}

	/* Style the input fields */
	.form-control {
		width: 100%;
		padding: 8px;
		border: 1px solid #ccc;
		border-radius: 4px;
		box-sizing: border-box;
		margin-top: 5px;
	}
</style>

<div class="text-center">
	<form asp-action="AssignParcel">
		<fieldset class="FormContent">

			<div class="row mb-3">
				<label asp-for="ParcelID" class="col-sm-3 col-form-label"></label>
				<div class="col-lg-9 col-md-7">
					<input asp-for="ParcelID" class="form-control" />
					<span asp-validation-for="ParcelID" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-3">
				<label asp-for="DeliveryManID" class="col-sm-3 col-form-label"></label>
				<div class="col-lg-9 col-md-7">
					<input asp-for="DeliveryManID" class="form-control" />
					<span asp-validation-for="DeliveryManID" class="text-danger"></span>
				</div>
			</div>

			<span style="color:red;">@TempData["ErrorMessage"]</span>
			<div class="row mb-3">
				<div class="">
					<input type="submit" value="Assign" class="btn btn-primary" />
				</div>
			</div>
		</fieldset>
	</form>
</div>

@if (Convert.ToBoolean(ViewData["Error"]))
{
	<h2 class="text-center text-danger">No Information found.</h2>
}

WEB_Assignment_IT02_Team7/Views/StationManager/CreateResponse.cshtml
@model WEB_Assignment_IT02_Team7.Models.FeedbackEnquiry

@{
    ViewData["Title"] = "CreateResponse";
}

<div class="createResponseForm">
    <h2 style="text-align:center;">Create Response</h2>
    <form asp-action="CreateResponse" method="post">
        <div class="form-group">
            <label>Feedback/Enquiry Content:</label>
            <textarea asp-for="Content" class="form-control" rows="8" readonly>@Html.Display("Content")</textarea>
        </div>
        <div class="form-group mt-5">
            <label>Enter Response Here:</label>
            <textarea asp-for="Response" class="form-control" rows="8" placeholder="Type your response here."></textarea>
            <span asp-validation-for="Response" class="text-danger mt-1"></span>
        </div>
        <div class="form-group">
            <button type="submit" value="Submit" class="btn btn-primary" style="margin-top: 20px;" asp-route-feedbackEnquiryID="@Model.FeedbackEnquiryID">Submit</button>
        </div>
    </form>
</div>

WEB_Assignment_IT02_Team7/Views/StationManager/DeliveryInformation.cshtml
@model WEB_Assignment_IT02_Team7.Models.ParcelViewModel

@{
    ViewData["Title"] = "DeliveryInformation";
}

<div class="text-center">
    <div class="searchForm">
        <h2 style="text-align:center;">Delivery Information</h2>
        <form asp-action="DeliveryInformation" method="post">
            <div class="form-group row">
                <label class="col-sm-5 col-form-label">Search By Parcel ID</label>
                <div class="col-sm-3">
                    <input type="number" min="1" step="1" class="form-control" asp-for="SearchedParcelID">
                </div>
                <div class="col-sm-3">
                    <button type="submit" name="submitButton" value="SearchParcel" class="btn btn-primary">Search</button>
                </div>
            </div>
            <div class="form-group row mt-3">
                <label class="col-sm-5 col-form-label">Search By Customer Name</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" asp-for="SearchedCustomerName">
                </div>
                <div class="col-sm-3">
                    <button type="submit" name="submitButton" value="SearchCustomer" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>
@if (Model.ParcelList != null)
{
    @if (Model.ParcelList.Count > 0)
    {
        <div class="deliveryInformationTable">
            <table class="table">
                <thead>
                    <tr>
                        <th>Parcel ID</th>
                        <th>Sender Name</th>
                        <th>Sender Tel No</th>
                        <th>Receiver Name</th>
                        <th>Receiver Tel No</th>
                        <th>Parcel Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ParcelList)
                    {
                        <tr>
                            <td>@item.ParcelID</td>
                            <td>@item.SenderName</td>
                            <td>@item.SenderTelNo</td>
                            <td>@item.ReceiverName</td>
                            <td>@item.ReceiverTelNo</td>
                            <td>
                                @if (item.DeliveryStatus == '0')
                                {
                                    <span class="text-warning">Pending Delivery</span>
                                }
                                else if (item.DeliveryStatus == '1')
                                {
                                    <span class="text-primary">Delivery to Destination in Progress</span>
                                }
                                else if (item.DeliveryStatus == '2')
                                {
                                    <span class="text-primary">Delivery to Airport in Progress</span>
                                }
                                else if (item.DeliveryStatus == '3')
                                {
                                    <span class="text-success">Delivery Completed</span>
                                }
                                else if (item.DeliveryStatus == '4')
                                {
                                    <span class="text-danger">Delivery Failed</span>
                                }
                                else
                                {
                                    <span class="text-muted">Unknown Status</span>
                                }
                            </td>
                            <td>
                                <a asp-action="ViewDeliveryHistory"
                       asp-controller="StationManager"
                       asp-route-parcelID="@item.ParcelID"
                                   class="btn btn-primary btn-sm btn-table">Verify</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div class="noDeliveryInformation">
            <h2 class="text-center text-danger">No Information found.</h2>
        </div>
    }
}
@if (Convert.ToBoolean(ViewData["Error"]))
{
    <div class="noDeliveryInformation">
        <h2 class="text-center text-danger">No Information found.</h2>
    </div>
}

WEB_Assignment_IT02_Team7/Views/StationManager/Index.cshtml
@{
    ViewData["Title"] = "Index";
    var role = Context.Session.GetString("Role");
    var name = Context.Session.GetString("Name");
}

<div class="container front-index-container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-8">
            <h2>Welcome @name!</h2>
            <h3>Here are the functions for @role:</h3>
            <ul class="list-group list-group-flush">
                <a href="~/StationManager/AssignParcel" class="list-group-item list-group-item-action">Assign Package</a>
                <a href="~/StationManager/DeliveryInformation" class="list-group-item list-group-item-action">Delivery Information</a>
                <a href="~/StationManager/RespondFeedback" class="list-group-item list-group-item-action">Respond Feedback</a>
            </ul>
        </div>
    </div>
</div>

WEB_Assignment_IT02_Team7/Views/StationManager/RespondFeedback.cshtml
@model IEnumerable<WEB_Assignment_IT02_Team7.Models.FeedbackEnquiry>

@{
    ViewData["Title"] = "RespondFeedback";
}

@if (Model.ToList().Count > 0)
{
    <div class="responseTable">
        <h2 class="text-center">Respond Feedback</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Feedback Enquiry ID</th>
                    <th>Member ID</th>
                    <th>Date Time Posted</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.FeedbackEnquiryID</td>
                        <td>@item.MemberID</td>
                        <td>@item.DateTimePosted</td>
                        <td>
                            @if (item.Status == '0')
                            {
                                <span class="text-warning">Pending Response</span>
                            }
                            else if (item.Status == '1')
                            {
                                <span class="text-primary">Closed</span>
                            }
                            else
                            {
                                <span class="text-muted">Unknown Status</span>
                            }
                        </td>
                        <td>
                            <a class="btn btn-primary btn-sm btn-table"
                       asp-action="CreateResponse"
                       asp-controller="StationManager"
                       asp-route-feedbackEnquiryID="@item.FeedbackEnquiryID">
                                Respond
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="noResponse">
        <h2 class="text-center text-danger">No Feedbacks to Respond.</h2>
    </div>
}

WEB_Assignment_IT02_Team7/Views/StationManager/ViewDeliveryHistory.cshtml
@model IEnumerable<WEB_Assignment_IT02_Team7.Models.DeliveryHistory>

@{
    ViewData["Title"] = "ViewDeliveryHistory";
}

@if (Model.ToList().Count > 0)
{
    <div class="deliveryHistoryTable">
        <h2 class="text-center">Delivery History</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Record ID</th>
                    <th>Parcel ID</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.RecordID</td>
                        <td>@item.ParcelID</td>
                        <td>@item.Description</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="noDeliveryHistory">
        <h2 class="text-center text-danger">No Delivery History</h2>
    </div>
}

WEB_Assignment_IT02_Team7/Views/StationManager/_StationManagerMenu.cshtml
<nav class="navbar navbar-expand-md navbar-light">
	<a class="navbar-brand" href="~/StationManager/Index">
		<img id="NPCSLogo" src="~/assets/DeliveryIcon.png" alt="NPCS Logo" style="width:50px" />
	</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#commonNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="commonNavbar">
		<ul class="navbar-nav me-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/StationManager/AssignParcel">
					Assign Package
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="~/StationManager/DeliveryInformation">Delivery Information</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="~/StationManager/RespondFeedback">Respond Feedback</a>
			</li>
		</ul>
		<ul class="navbar-nav ms-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/StationManager/LogOut">Log Out</a>
			</li>
		</ul>
	</div>
</nav>