WEB_Assignment_IT02_Team7/Controllers/DeliveryManController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Net.Http;
using System.Xml.Linq;
using WEB_Assignment_IT02_Team7.DAL;
using WEB_Assignment_IT02_Team7.Models;
using System.Globalization;

namespace WEB_Assignment_IT02_Team7.Controllers
{
	public class DeliveryManController : Controller
	{
		//Create instance
		private DeliveryManDAL DeliveryManContext = new DeliveryManDAL();
		private List<string> FailureTypes = new List<string>()
		{
			"Receiver not found", "Wrong delivery address", "Parcel damaged", "Other"
		};

		//Redirect user back to Index - Home if user role != Delivery Man
		//Direct user to Index view if role is Delivery Man
		public ActionResult Index()
		{
			if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Delivery Man"))
			{
				return RedirectToAction("Index", "Home");
			}

			return View();
		}

		//Retrieve list of parcels assigned to delivery man and pass it to the AssignedParcelList
		public ActionResult AssignedParcels()
		{
			if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Delivery Man"))
			{
				return RedirectToAction("Index", "Home");
			}
			List<Parcel> AssignedParcelList = DeliveryManContext.GetParcelsForDeliveryMan(HttpContext.Session.GetInt32("StaffID"));
			return View(AssignedParcelList);
		}

		//If parcelID is null, redirect user to AssignedParcels
		//If not update the UpdateDeliveryStatus method of DeliveryManContext
		public ActionResult UpdateDeliveryStatus(Parcel parcel)
		{
			DeliveryHistory deliveryHistory = new DeliveryHistory();

			if (parcel.ParcelID == null)
			{
				RedirectToAction("AssignedParcels");
			}

			else if (parcel.ToCountry == parcel.FromCountry)
			{
				deliveryHistory.Description = $"Parcel delivered successfully by {HttpContext.Session.GetString("LoginID")} on {DateTime.Now.ToString("d MMM yyyy h:mmtt", CultureInfo.CreateSpecificCulture("en-GB"))}.";
				DeliveryManContext.UpdateDeliveryStatusLocal(parcel, deliveryHistory);
				return RedirectToAction("Index");
			}

			else if (parcel.ToCountry != parcel.FromCountry)
			{
				deliveryHistory.Description = $"Parcel delivered to airport by {HttpContext.Session.GetString("LoginID")} on {DateTime.Now.ToString("d MMM yyyy h:mmtt", CultureInfo.CreateSpecificCulture("en-GB"))}.";
				DeliveryManContext.UpdateDeliveryStatusLocal(parcel, deliveryHistory);
				DeliveryManContext.UpdateDeliveryStatusOverSeas(parcel, deliveryHistory);
				return RedirectToAction("Index");
			}

			return View(AssignedParcels);

		}

		public ActionResult FailDeliveryStatus(int? parcelID)
		{
			if (parcelID == null)
			{
				RedirectToAction("AssignedParcels");
			}

			DateTime date = DateTime.Now;
			DeliveryManContext.FailDeliveryStatus(parcelID);
			return RedirectToAction("Index");
		}

		//public ActionResult DeliverFailureReport()
		//{
		//    ViewData["FailureTypes"] = DFTypes();
		//    List<DeliveryFailureReport> deliveryFailureReports = DeliveryManContext.GetDeliveryFailureReport();
		//    return View(deliveryFailureReports);
		//}



		public ActionResult LogOut()
		{
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home");
		}

		private List<SelectListItem> DFTypes()
		{
			List<SelectListItem> FailureTypes = new List<SelectListItem>
			{
				new SelectListItem
				{
					Value = "0",
					Text = "Receiver not found"
				},
				new SelectListItem
				{
					Value = "1",
					Text = "Wrong delivery address"
				},
				new SelectListItem
				{
					Value = "2",
					Text = "Parcel damaged"
				},
				new SelectListItem
				{
					Value = "3",
					Text = "Other"
				},

			};
			return FailureTypes;
		}


		public ActionResult DeliverFailureReport()
		{
			if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Delivery Man"))
			{
				return RedirectToAction("Index", "Home");
			}

			List<DeliveryFailureReport> deliveryFailureReports = DeliveryManContext.GetDeliveryFailureReport();

			ViewData["NewFailureTypes"] = FailureTypes;
            ViewBag.FailureTypes = DFTypes();

            var model = new DeliveryFailureReport();
            model.failuretype = '0'; // Set a default failure type (optional)
            ViewBag.FailureTypes = DFTypes();
            return View(model);

		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult DeliverFailureReport(DeliveryFailureReport deliveryFailureReport)
		{
            ViewBag.FailureTypes = DFTypes();
			List<Parcel> failparcel = new List<Parcel>();
			failparcel = DeliveryManContext.GetFailedDelivery();
            List<char> failstatuslist = new List<char> { '1', '2', '3', '4' };
            char failstatus = '4';

            if (ModelState.IsValid)
			{
				if (DeliveryManContext.CheckDeliveryFailure(deliveryFailureReport.parcelid)==true)
				{
                    return RedirectToAction("Index");
                }


				foreach (var item in failparcel)
				{
					if (item.DeliveryStatus == failstatus)
					{
						if(item.ParcelID == deliveryFailureReport.parcelid)
						{
                            foreach (var failchar in failstatuslist)
                            {
                                if (failchar == deliveryFailureReport.failuretype)
                                {

                                    if (DeliveryManContext.CheckDeliveryFailure(deliveryFailureReport.parcelid) == false)
                                    {


                                        deliveryFailureReport.deliverymanid = Convert.ToInt32(HttpContext.Session.GetInt32("StaffID"));
                                        deliveryFailureReport.failuretype = deliveryFailureReport.failuretype.ToString()[0];
                                        deliveryFailureReport.datecreated = DateTime.Now;

                                        deliveryFailureReport.reportid = DeliveryManContext.AddDeliveryFailureReport(deliveryFailureReport);
                                        return RedirectToAction("Index");

                                    }
                                }
                            }
                        }
                    }

				}
            }
			return View("Index");

		}

	}
}

WEB_Assignment_IT02_Team7/Views/DeliveryMan/AssignedParcels.cshtml
@model IEnumerable<WEB_Assignment_IT02_Team7.Models.Parcel>

@{
    ViewData["Title"] = "AssignedParcels";
}

@if (Model.ToList().Count > 0)
{
    <div class="assignedParcels">
        <h2 class="text-center">Parcels Assigned to Delivery Man</h2>
        <table class="table">
            <tr>
                <th>Parcel ID</th>
                <th>Delivery Type</th>
                <th>Target Delivery DateTime</th>
                <th>Delivery Status</th>
                <th>Success</th>
                <th>Failed</th>
            </tr>
            @foreach (var parcel in Model)
            {
                <tr>
                    <td>@parcel.ParcelID</td>
                    <td>
                        @if (@parcel.ToCountry == @parcel.FromCountry)
                        {
                            <span>Local</span>
                        }
                        else
                        {
                            <span>Overseas</span>
                        }

                    </td>
                    <td>@parcel.TargetDeliveryDate</td>
                    <td>@parcel.DeliveryStatus</td>
                    <!--Link to Controller-->
                    <td><a asp-action="UpdateDeliveryStatus" asp-route-parcelID="@parcel.ParcelID" asp-route-fromCountry="@parcel.FromCountry" asp-route-toCountry="@parcel.ToCountry" class="btn btn-primary btn-sm btn-table">Update</a></td>
                    <td><a asp-action="FailDeliveryStatus" asp-route-parcelID="@parcel.ParcelID" class="btn btn-primary btn-sm btn-table">Failed </a></td>

                </tr>
            }
        </table>
    </div>
}
else
{
    <div class="noAssignedParcels">
        <p>No parcels assigned to this delivery man.</p>
    </div>
}

WEB_Assignment_IT02_Team7/Views/DeliveryMan/DeliverFailureReport.cshtml
@model WEB_Assignment_IT02_Team7.Models.DeliveryFailureReport

@{
    ViewData["Title"] = "DeliverFailureReport";
}

<style>
    /* styles.css */
    .form-container {
        background-color: #f2f2f2; /* Light grey background color */
        padding: 20px; /* Add some padding to create spacing between form elements and the container */
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

        .form-control:focus {
            outline: none;
            border-color: #007bff;
            box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
        }

    .form-group label {
        font-weight: bold;
        display: block;
    }

    textarea.form-control {
        resize: vertical;
    }

    .dmfr {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 90vh; /* Ensure the container takes at least the full height of the viewport */
    }

    .form-wrapper {
        padding: 20px; /* Add some padding to create spacing within the wrapper */
        margin: 0 auto; /* Set margin to auto to center the form horizontally */
    }
</style>

<div class="dmfr form-wrapper">
    @using (Html.BeginForm("DeliverFailureReport", "DeliveryMan", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.parcelid)
            @Html.TextBoxFor(model => model.parcelid, new { @class = "form-control", @placeholder = "Enter Parcel ID" })
            @Html.ValidationMessageFor(model => model.parcelid)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.failuretype)
            @Html.TextBoxFor(model => model.failuretype, new { @class = "form-control", @placeholder = "Enter Failure Type (Single Digit)" })
            @Html.ValidationMessageFor(model => model.failuretype)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description)
            @Html.TextAreaFor(model => model.description, new { @class = "form-control", @placeholder = "Enter Description", rows = 4 })
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>

WEB_Assignment_IT02_Team7/Views/DeliveryMan/Index.cshtml
@{
    ViewData["Title"] = "Index";
    var role = Context.Session.GetString("Role");
    var name = Context.Session.GetString("Name");
}

<div class="container front-index-container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-8">
            <h2>Welcome @name!</h2>
            <h3>Here are the functions for @role:</h3>
            <ul class="list-group list-group-flush">
                <a href="~/DeliveryMan/AssignedParcels" class="list-group-item list-group-item-action">Assigned Parcels</a>
                <a href="~/DeliveryMan/DeliverFailureReport" class="list-group-item list-group-item-action">Delivery Failure Report</a>
            </ul>
        </div>
    </div>
</div>

WEB_Assignment_IT02_Team7/Views/DeliveryMan/_DeliveryManMenu.cshtml
<nav class="navbar navbar-expand-md navbar-light">
	<a class="navbar-brand" href="~/DeliveryMan/Index">
		<img id="NPCSLogo" src="~/assets/DeliveryIcon.png" alt="NPCS Logo" style="width:50px" />
	</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#commonNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="commonNavbar">
		<ul class="navbar-nav me-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/DeliveryMan/AssignedParcels">View Delivery Records</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="~/DeliveryMan/DeliverFailureReport">Delivery Failure Report</a>
			</li>
		</ul>
		<ul class="navbar-nav ms-auto">
			<li class="nav-item">
				<a class="nav-link" href="~/DeliveryMan/LogOut">Log Out</a>
			</li>
		</ul>
	</div>
</nav>